version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: mongo_db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - mongo_db:/data/db

  # Node.js UI
  api:
    container_name: Node_js_container
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      MONGODB_URL: mongodb://mongo_db:27017/vipin
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}